INSERT INTO "PUBLIC".CATEGORIA(DESCRICAO) VALUES('INFORMATICA');
INSERT INTO "PUBLIC".CATEGORIA(DESCRICAO) VALUES('ELETRODOMESTICOS');
INSERT INTO "PUBLIC".CATEGORIA(DESCRICAO) VALUES('MOVEIS');

INSERT INTO "PUBLIC".CATEGORIA(DESCRICAO,CATEGORIA_PAI_ID) VALUES('COMPUTADORES',1);
INSERT INTO "PUBLIC".CATEGORIA(DESCRICAO,CATEGORIA_PAI_ID) VALUES('NOTEBOOKS',1);
INSERT INTO "PUBLIC".CATEGORIA(DESCRICAO,CATEGORIA_PAI_ID) VALUES('TABLETES',1);
INSERT INTO "PUBLIC".CATEGORIA(DESCRICAO,CATEGORIA_PAI_ID) VALUES('MONITORES',1);
INSERT INTO "PUBLIC".CATEGORIA(DESCRICAO,CATEGORIA_PAI_ID) VALUES('IMPRESSORAS',1);
INSERT INTO "PUBLIC".CATEGORIA(DESCRICAO,CATEGORIA_PAI_ID) VALUES('ACESSORIOS',1);

INSERT INTO "PUBLIC".CATEGORIA(DESCRICAO,CATEGORIA_PAI_ID) VALUES('AR CONDICIONADO',2);
INSERT INTO "PUBLIC".CATEGORIA(DESCRICAO,CATEGORIA_PAI_ID) VALUES('FOGOES',2);
INSERT INTO "PUBLIC".CATEGORIA(DESCRICAO,CATEGORIA_PAI_ID) VALUES('FORNO ELETRICO',2);
INSERT INTO "PUBLIC".CATEGORIA(DESCRICAO,CATEGORIA_PAI_ID) VALUES('MICROONDAS',2);
INSERT INTO "PUBLIC".CATEGORIA(DESCRICAO,CATEGORIA_PAI_ID) VALUES('GELADEIRA',2);
INSERT INTO "PUBLIC".CATEGORIA(DESCRICAO,CATEGORIA_PAI_ID) VALUES('LIQUIDIFICADOR',2);

INSERT INTO "PUBLIC".CATEGORIA(DESCRICAO,CATEGORIA_PAI_ID) VALUES('MESA',3);
INSERT INTO "PUBLIC".CATEGORIA(DESCRICAO,CATEGORIA_PAI_ID) VALUES('CADEIRA',3);
INSERT INTO "PUBLIC".CATEGORIA(DESCRICAO,CATEGORIA_PAI_ID) VALUES('ARMARIO',3);
INSERT INTO "PUBLIC".CATEGORIA(DESCRICAO,CATEGORIA_PAI_ID) VALUES('RACKS',3);
INSERT INTO "PUBLIC".CATEGORIA(DESCRICAO,CATEGORIA_PAI_ID) VALUES('SOFAS',3);
INSERT INTO "PUBLIC".CATEGORIA(DESCRICAO,CATEGORIA_PAI_ID) VALUES('ESTANTES',3);