INSERT INTO "PUBLIC".CATEGORIA (DESCRICAO) VALUES('LIMPEZA');
INSERT INTO "PUBLIC".CATEGORIA (DESCRICAO) VALUES('BISCOITO');
INSERT INTO "PUBLIC".CATEGORIA (DESCRICAO) VALUES('REFRIGERANTE');
INSERT INTO "PUBLIC".CATEGORIA (DESCRICAO) VALUES('HIGIENE');
-- USUARIO
INSERT INTO "PUBLIC".USUARIO (LOGIN,NIVELACESSO,NOME,SENHA)
VALUES ('MOISES.SILVA','ADMINISTRADOR','MOISES JUVENAL DA SILVA','123456');
--PRODUTO
INSERT INTO "PUBLIC".PRODUTO(CATEGORIA,NOME,QUANTIDADEESTOQUE,
